name: Poetry

on: [push]

jobs:

  setup:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: Gr1N/setup-poetry@v7
      - run: poetry --version
        env:
          POETRY_HTTP_BASIC_MY_REPOSITORY_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}